name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        node-version: [12.x]
    env: 
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: act10ns/slack@v1
      with:
          status: starting
          channel: '#testing-for-punnet'
          if: always()
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      id: checkout
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      id: npm_install
      run: npm install
    - name: npm build
      id: npm_build
      run: npm run build --if-present
    - name: npm test
      id: npm_test
      run: npm test -- --coverage
    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() 
